language: node.js
node_js:
  - "12"

install:
  - npm install -g serverless
  - travis_retry npm install

script:
  - serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_ID" --secret "$AWS_SECRET_KEY" --profile $AWS_PROFILE
  - serverless deploy --aws-profile $AWS_PROFILE
